### PR TITLE
Added installation instructions (issue#9), a note on spaCy's models(i…

### PR DESCRIPTION
**Pull request by KGBicheno**
…ssue#17), corrected an error in the usage example (issue#81) and proofed the Markdown for adherence to the MD specification.

### CODE REVIEW

**Comment by KGBicheno** [comment]
Sorry if I've missed a step in the process. Also let me know if you'd like more detail in the installation process and I'll add it, no probs.

**Comment by KGBicheno** [comment]
If this pull does fail, I'd love some feedback, just because it is my first and I'd love to improve.

**Comment by anneschuth** [comment]
@KGBicheno thanks for contributing, much appreciated!

The PR is failing on linting issues, you can see details on our CI/CD: https://travis-ci.com/github/textpipe/textpipe/builds/186823330

**Comment by KGBicheno** [comment]
Cheers, will fix asap when I get home :D

**Comment by KGBicheno** [comment]
@anneschuth Hi again, I've looked at the Travis logs and it looks like the problems are in doc.py, operation.py, and wrappers.py, and both failed linting before my PR (from about 28 days ago). 

Should I close my PR until those are resolved? I'm not familiar with the code there and I'm not sure I have time to learn an unknown amount of the code base to fix it so I can update the README sorry :(

**Comment by anneschuth** [comment]
Oh, if those issues don't come from your changes you should certainly not fix them in this PR, sorry, I hadn't looked at the content of your PR at all yet. 

Please leave your PR open. I'll fix the existing issues, retrigger a build of your PR and merge yours after.

**Review by anneschuth — APPROVED** [review]

**Comment by KGBicheno** [comment]
Oh, cool, sorry about that. Cheers for looking into that. Sorry, like I said, this was my first ever Pull request so I'm a little shaky on protocol.

**Comment by KGBicheno** [comment]
I'll come back once I've got more time and poke around for other first-time friendly issues I can look into and add see If I can't be added as a collaborator :D

**Pull request merged**
