### PR TITLE
Setup Travis and Codacity

### LINKED ISSUE #1: Setup CI
Currently running on an internal Jenkins instance. Maybe transfer to Travis?

Tests run with:
```
# Install cld2-cffi package with an additional CFLAG
CFLAGS="-Wno-narrowing" pip3 install --quiet cld2-cffi

# Install requirements
pip3 install --quiet --requirement requirements.txt

# Install and run pylint
pip3 install --quiet --upgrade pylint 
python3 -m pylint -f parseable textpipe | tee pylint.out

# Download languages needed for testing
python3 -m spacy download nl > /dev/null
python3 -m spacy download en > /dev/null

# Run test with pytest, including doctests
pip3 install --quiet --upgrade pytest
python3 -m pytest --doctest-modules --junit-xml=pytest.xml

# Run unit tests again, but with nose for coverage report
pip3 install --quiet --upgrade nosexcover
python3 -m nose --with-doctest --with-xcoverage --with-xunit --cover-package=textpipe --cover-erase 2> /dev/null
```

### PR DESCRIPTION
**Pull request by anneschuth**
Setup Travis as CI to resolve #1.

### CODE REVIEW

**Comment by dodijk** [comment]
I think we need to check the [result of pylint for an exit code](https://fullvalence.com/2016/11/22/travis-and-pylint/).

**Comment by anneschuth** [comment]
Thanks, that should work! I was looking for a way ensure coverage would only go up.

**Comment by dodijk** [comment]
Yeah, there's quite a bit more we can get out of the `pylint` output, but it seems that it is not really integrated with Travis ATM. For coverage we can use consider http://coveralls.io. I don't see an easily solution for the `pylint` score. A possible solution might be to have our Jenkins report back on Github?  But I'd rather have an external service do this.

**Comment by anneschuth** [comment]
I've tried coveralls, integrations seemed non-trivial. Trying codacity now. I'd propose to look into this separate from this PR.

**Pull request merged**
